package;

import flixel.FlxSprite;

#if windows
import Sys;
import sys.FileSystem;
#end

#if sys
import sys.io.File;
import haxe.io.Path;
import openfl.utils.ByteArray;
import flash.display.BitmapData;
import sys.FileSystem;
#end

using StringTools;

class HealthIcon extends FlxSprite
{
	/**
	 * Used for FreeplayState! If you use it elsewhere, prob gonna annoying
	 */
	public var sprTracker:FlxSprite;

	public var char:String = 'bf';
	public var isPlayer:Bool = false;
	public var isOldIcon:Bool = false;

	public function new(?char:String = 'bf', ?isPlayer:Bool = false)
	{
		super();

		this.char = char;
		this.isPlayer = isPlayer;

		useOldSystem(char);
		scrollFactor.set();
	}

	public function changeIcon(char:String)
	{
		if (!FileSystem.exists(Paths.image('icons/icon-' + char)))
			char = 'face';

		var rawPic = BitmapData.fromFile(Paths.image('icons/icon-'+char));
		loadGraphic(rawPic, true, 150, 150);

		if (char.endsWith('-pixel') || char.startsWith('senpai') || char.startsWith('spirit'))
			antialiasing = false;
		else
			antialiasing = true;

		animation.add(char, [0, 1], 0, false, isPlayer);
		animation.play(char);
	}

	public function useOldSystem(char:String)
	{
		loadGraphic(Paths.image('iconGrid'), true, 150, 150);

		antialiasing = true;
		animation.add('bf', [0, 1], 0, false, isPlayer);
		animation.add('bf-car', [0, 1], 0, false, isPlayer);
		animation.add('bf-christmas', [0, 1], 0, false, isPlayer);
		animation.add('bf-fnf-switch', [0, 1], 0, false, isPlayer);
		animation.add('bf-updike', [0, 1], 0, false, isPlayer);
		animation.add('bf-ghost', [0, 1], 0, false, isPlayer);
		animation.add('bfHalloween', [0, 1], 0, false, isPlayer);
		animation.add('spooky', [2, 3], 0, false, isPlayer);
		animation.add('bf-spooky', [2, 3], 0, false);
		animation.add('pico', [4, 5], 0, false, isPlayer);
		animation.add('gf-pico', [4, 5], 0, false, isPlayer);
		animation.add('mom', [6, 7], 0, false, isPlayer);
		animation.add('mom-car', [6, 7], 0, false, isPlayer);
		animation.add('mom-shaded', [6, 7], 0, false, isPlayer);
		animation.add('tankman', [8, 9], 0, false, isPlayer);
		animation.add('face', [10, 11], 0, false, isPlayer);
		animation.add('dad', [12, 13], 0, false, isPlayer);
		animation.add('dad-flipped', [12, 13], 0, false, isPlayer);
		animation.add('bf-old', [14, 15], 0, false, isPlayer);
		animation.add('gf', [16, 17], 0, false, isPlayer);
		animation.add('bf-gf', [16, 17], 0, false, isPlayer);
		animation.add('bf-gf-lullaby', [16, 17], 0, false, isPlayer);
		animation.add('gf-standing', [16, 17], 0, false, isPlayer);
		animation.add('gf-standing-halloween', [16, 17], 0, false, isPlayer);
		animation.add('gf-crucified', [16, 17], 0, false, isPlayer);
		animation.add('parents-christmas', [18,19], 0, false, isPlayer);
		animation.add('monster', [20, 21], 0, false, isPlayer);
		animation.add('monster-christmas', [20, 21], 0, false, isPlayer);
		animation.add('bf-pixel', [22, 23], 0, false, isPlayer);
		animation.add('garcello', [24, 25], 0, false, isPlayer);
		animation.add('playable-garcello', [24, 25], 0, false, isPlayer);
		animation.add('tricky', [26, 27], 0, false, isPlayer);
		animation.add('bf-annie', [28, 29], 0, false, isPlayer);
		animation.add('zardy', [30, 31], 0, false, isPlayer);
		animation.add('whitty', [32, 33], 0, false, isPlayer);
		animation.add('whitty-minus', [32, 33], 0, false, isPlayer);
		animation.add('hex', [34, 35], 0, false, isPlayer);
		animation.add('bf-carol', [36, 37], 0, false, isPlayer);
		animation.add('gf4', [36, 37], 0, false, isPlayer);
		animation.add('exgf', [38, 39], 0, false, isPlayer);
		animation.add('bf-exgf', [38, 39], 0, false, isPlayer);
		animation.add('hd-senpai', [40, 41], 0, false, isPlayer);
		animation.add('bf-hd-senpai-angry', [40, 41], 0, false, isPlayer);
		animation.add('bf-hd-senpai-angry-night', [40, 41], 0, false, isPlayer);
		animation.add('hd-senpai-angry', [40, 41], 0, false, isPlayer);
		animation.add('hd-senpai-fear', [41], 0, false, isPlayer);
		animation.add('bf-sarv', [42, 43], 0, false, isPlayer);
		animation.add('sarvente', [42, 43], 0, false, isPlayer);
		animation.add('sarvente-dark', [42, 43], 0, false, isPlayer);
		animation.add('ruv', [44, 45], 0, false, isPlayer);
		animation.add('bf-sky', [46, 47], 0, false, isPlayer);
		animation.add('sky-happy', [46, 47], 0, false, isPlayer);
		animation.add('sky-purehappiness', [46], 0, false, isPlayer);
		animation.add('drunk-annie', [48, 49], 0, false, isPlayer);
		animation.add('drunk-annie-blue', [48, 49], 0, false, isPlayer);
		animation.add('matt', [50, 51], 0, false, isPlayer);
		animation.add('miku', [52, 53], 0, false, isPlayer);
		animation.add('monika', [54, 55], 0, false, isPlayer);
		animation.add('selever', [56, 57], 0, false, isPlayer);
		animation.add('bf-frisk', [58, 59], 0, false, isPlayer);
		animation.add('bf-sans', [60, 61], 0, false, isPlayer);
		animation.add('kapi', [62, 63], 0, false, isPlayer);
		animation.add('liz', [64, 65], 0, false, isPlayer);
		animation.add('tord', [66, 67], 0, false, isPlayer);
		animation.add('agoti', [68, 69], 0, false, isPlayer);
		animation.add('tabi', [70, 71], 0, false, isPlayer);
		animation.add('tom', [72, 73], 0, false, isPlayer);
		animation.add('cassandra', [74, 75], 0, false, isPlayer);
		animation.add('whittyCrazy', [76, 77], 0, false, isPlayer);
		animation.add('sarvente-lucifer', [78, 79], 0, false, isPlayer);
		animation.add('knuckles', [80, 81], 0, false, isPlayer);
		animation.add('lila', [82, 83], 0, false, isPlayer);
		animation.add('garcellotired', [84, 85], 0, false, isPlayer);
		animation.add('garcellotired-blue', [84, 85], 0, false, isPlayer);
		animation.add('gura-amelia', [86, 87], 0, false, isPlayer);
		animation.add('gura-amelia-walfie', [86, 87], 0, false, isPlayer);
		animation.add('botan', [88, 89], 0, false, isPlayer);
		animation.add('bf-dad', [90, 91], 0, false, isPlayer);
		animation.add('bf-mom', [92, 93], 0, false, isPlayer);
		animation.add('bf-mom-car', [92, 93], 0, false, isPlayer);
		animation.add('nene', [94, 95], 0, false, isPlayer);
		animation.add('nene2', [94, 95], 0, false, isPlayer);
		animation.add('bf-blantad', [96, 97], 0, false, isPlayer);
		animation.add('blantad-new', [96, 97], 0, false, isPlayer);
		animation.add('blantad-scream', [96, 97], 0, false, isPlayer);
		animation.add('blantad-watch', [96, 97], 0, false, isPlayer);
		animation.add('blantad-handscutscene', [96, 97], 0, false, isPlayer);
		animation.add('blantad-handscutscene2', [96, 97], 0, false, isPlayer);
		animation.add('blantad-teleport', [96, 97], 0, false, isPlayer);
		animation.add('hd-senpai-dark', [98], 0, false, isPlayer);
		animation.add('bf-hd-senpai-dark', [98], 0, false, isPlayer);
		animation.add('matt-angry', [99], 0, false, isPlayer);
		animation.add('uganda-knuckles', [100], 0, false, isPlayer);
		animation.add('hd-spiritnotmad', [101], 0, false, isPlayer);
		animation.add('hd-spirit', [101,102], 0, false, isPlayer);
		animation.add('sky-mad', [103, 592], 0, false, isPlayer);
		animation.add('senpaighosty', [104], 0, false, isPlayer);
		animation.add('tankman-sad', [105, 8], 0, false, isPlayer);
		animation.add('tankman-sad-blue', [105, 8], 0, false, isPlayer);
		animation.add('monika-angry', [106, 107], 0, false, isPlayer);
		animation.add('anchor', [108,109], 0, false, isPlayer);
		animation.add('anchor-bowl', [108,109], 0, false, isPlayer);
		animation.add('roro', [110,111], 0, false, isPlayer);
		animation.add('agoti-mad', [112,113], 0, false, isPlayer);
		animation.add('miku-mad', [114,115], 0, false, isPlayer);
		animation.add('brother', [116,117], 0, false, isPlayer);
		animation.add('pompom-mad', [118,119], 0, false, isPlayer);
		animation.add('chara', [120,121], 0, false, isPlayer);
		animation.add('tabi-crazy', [122,123], 0, false, isPlayer);
		animation.add('sunday', [124,125], 0, false, isPlayer);
		animation.add('sunday-guitar', [124,125], 0, false, isPlayer);
		animation.add('bitdadcrazy', [126], 0, false, isPlayer);
		animation.add('dad-sad-pixel-white', [127], 0, false, isPlayer);
		animation.add('bf-pixeld4', [128], 0, false, isPlayer);
		animation.add('bf-pixeld4BSide', [129], 0, false, isPlayer);
		animation.add('bitdad', [130], 0, false, isPlayer);
		animation.add('bitdadBSide', [131], 0, false, isPlayer);
		animation.add('senpai-giddy', [132], 0, false, isPlayer);
		animation.add('bf-tankman-pixel', [133], 0, false, isPlayer);
		animation.add('miku-pixel', [134], 0, false, isPlayer);
		animation.add('jackson', [135], 0, false, isPlayer);
		animation.add('mario-angry', [136], 0, false, isPlayer);
		animation.add('bf-pico-pixel', [137], 0, false, isPlayer);
		animation.add('bf-sonic-pixel', [138], 0, false, isPlayer);
		animation.add('bf-tom-pixel', [139], 0, false, isPlayer);
		animation.add('bf-rico-pixel', [140], 0, false, isPlayer);
		animation.add('colt', [141], 0, false, isPlayer);
		animation.add('colt-angry', [141], 0, false, isPlayer);
		animation.add('colt-angryd2', [141], 0, false, isPlayer);
		animation.add('colt-angryd2corrupted', [141], 0, false, isPlayer);
		animation.add('monster-pixel', [142], 0, false, isPlayer);
		animation.add('spooky-pixel', [143], 0, false);
		animation.add('bf-wright-pixel', [144], 0, false, isPlayer);
		animation.add('kristoph-angry', [145], 0, false, isPlayer);
		animation.add('bf-gf-pixel', [146], 0, false, isPlayer);
		animation.add('bf-sans-pixel', [147], 0, false, isPlayer);
		animation.add('chara-pixel', [148], 0, false, isPlayer);
		animation.add('gura-amelia-pixel', [149], 0, false, isPlayer);
		animation.add('bf-botan-pixel', [150], 0, false, isPlayer);
		animation.add('bf-whitty-pixel', [151], 0, false, isPlayer);
		animation.add('agoti-pixel', [152], 0, false, isPlayer);
		animation.add('tabi-pixel', [153], 0, false, isPlayer);
		animation.add('green-monika', [154], 0, false, isPlayer);
		animation.add('empty', [155], 0, false, isPlayer);
		animation.add('template', [155], 0, false, isPlayer);
		animation.add('neon', [156], 0, false, isPlayer);
		animation.add('neon-bigger', [156], 0, false, isPlayer);
		animation.add('monika-jumpscare', [157], 0, false, isPlayer);
		animation.add('baldi-angry-pixel', [158], 0, false, isPlayer);
		animation.add('mangle-angry', [159], 0, false, isPlayer);
		animation.add('bf-tankman-pixel-plain', [160], 0, false, isPlayer);
		animation.add('kou', [161, 162], 0, false, isPlayer);
		animation.add('henry', [163, 164], 0, false, isPlayer);
		animation.add('shaggy', [165, 166], 0, false, isPlayer);
		animation.add('bf-lexi', [167, 168], 0, false, isPlayer);
		animation.add('monster-pixel-look', [169], 0, false, isPlayer);
		animation.add('bf1', [170, 171], 0, false, isPlayer);
		animation.add('bf-aloe', [170, 171], 0, false, isPlayer);
		animation.add('bf-aloe-car', [170, 171], 0, false, isPlayer);
		animation.add('bf-senpai-flippin', [172, 173], 0, false, isPlayer);
		animation.add('gf2', [172, 173], 0, false, isPlayer);
		animation.add('bf2', [172, 173], 0, false, isPlayer);
		animation.add('bf-peridot', [174, 175], 0, false, isPlayer);
		animation.add('bf3', [172, 173], 0, false, isPlayer);
		animation.add('bf-smol-whitty', [176, 177], 0, false, isPlayer);
		animation.add('bf4', [176, 177], 0, false, isPlayer);
		animation.add('bf-starzchan', [178, 179], 0, false, isPlayer);
		animation.add('bf5', [178, 179], 0, false, isPlayer);
		animation.add('gfandbf', [180, 181], 0, false, isPlayer);
		animation.add('gfandbf-fear', [180], 0, false, isPlayer);
		animation.add('gf1', [180, 181], 0, false, isPlayer);
		animation.add('senpai', [182, 183], 0, false, isPlayer);
		animation.add('senpai-z', [182, 183], 0, false, isPlayer);
		animation.add('bf-senpai-pixel', [182, 183], 0, false, isPlayer);
		animation.add('senpai-angry', [183], 0, false, isPlayer);
		animation.add('bf-senpai-pixel-angry', [183], 0, false, isPlayer);
		animation.add('agoti-glitcher', [184, 185], 0, false, isPlayer);
		animation.add('agoti-wire', [186, 187], 0, false, isPlayer);
		animation.add('tabi-wire', [188, 189], 0, false, isPlayer);
		animation.add('tabi-glitcher', [190, 191], 0, false, isPlayer);
		animation.add('miku-mad-christmas', [192, 193], 0, false, isPlayer);
		animation.add('demoncass', [194, 195], 0, false, isPlayer);
		animation.add('coco', [196, 197], 0, false, isPlayer);
		animation.add('coco-car', [196, 197], 0, false, isPlayer);
		animation.add('updike', [198, 199], 0, false, isPlayer);
		animation.add('rebecca', [200, 201], 0, false, isPlayer);
		animation.add('spirit', [202, 203], 0, false, isPlayer);
		animation.add('crazygf', [204], 0, false, isPlayer);
		animation.add('monika-finale', [205], 0, false, isPlayer);
		animation.add('lane', [206, 207], 0, false, isPlayer);
		animation.add('bob', [208, 209], 0, false, isPlayer);
		animation.add('opheebop', [210, 211], 0, false, isPlayer);
		animation.add('impostor', [212, 213], 0, false, isPlayer);
		animation.add('impostor2', [212, 213], 0, false, isPlayer);
		animation.add('neko-crazy', [214, 215], 0, false, isPlayer);
		animation.add('bf-confused', [216, 1], 0, false, isPlayer);
		animation.add('boygf', [217], 0, false, isPlayer);
		animation.add('momosuzu', [218], 0, false, isPlayer);
		animation.add('bf-nene', [218, 219], 0, false, isPlayer);
		animation.add('bf-nene-scream', [218, 219], 0, false, isPlayer);
		animation.add('girlbf', [220, 221], 0, false, isPlayer);
		animation.add('henry-angry', [222, 223], 0, false, isPlayer);
		animation.add('lane-pixel', [224], 0, false, isPlayer);
		animation.add('blantad-pixel', [225], 0, false, isPlayer);
		animation.add('bf-rincewind', [226, 227], 0, false, isPlayer);
		animation.add('bf-pico', [228, 229], 0, false, isPlayer);
		animation.add('bf-ena', [230, 231], 0, false, isPlayer);
		animation.add('bf-chris', [232, 233], 0, false, isPlayer);
		animation.add('bf-ryuko', [234, 235], 0, false, isPlayer);
		animation.add('bf-omori', [236, 237], 0, false, isPlayer);
		animation.add('bf-drip', [238, 239], 0, false, isPlayer);
		animation.add('bf-narancia', [240, 241], 0, false, isPlayer);
		animation.add('bf-troll', [242, 243], 0, false, isPlayer);
		animation.add('gf-kanna', [244], 0, false, isPlayer);
		animation.add('gf3', [244], 0, false, isPlayer);
		animation.add('gf-rincewind', [245], 0, false, isPlayer);
		animation.add('gf-lapis', [246], 0, false, isPlayer);
		animation.add('gf-moony', [247], 0, false, isPlayer);
		animation.add('gf-kaity', [248], 0, false, isPlayer);
		animation.add('gf-lemon', [249], 0, false, isPlayer);
		animation.add('matt2', [250, 251], 0, false, isPlayer);
		animation.add('tord2', [252, 253], 0, false, isPlayer);
		animation.add('eddsworld-switch', [252, 253], 0, false, isPlayer);
		animation.add('tom2', [254, 255], 0, false, isPlayer);
		animation.add('edd2', [256, 257], 0, false, isPlayer);
		animation.add('gf-drip', [258, 259], 0, false, isPlayer);
		animation.add('gf-aubrey', [260], 0, false, isPlayer);
		animation.add('gf-chara', [261], 0, false, isPlayer);
		animation.add('gf-troll', [262], 0, false, isPlayer);
		animation.add('gf-fugo', [263], 0, false, isPlayer);
		animation.add('tankman-happy', [264, 9], 0, false, isPlayer);
		animation.add('bf-hd-senpai-giddy', [40, 265], 0, false, isPlayer);
		animation.add('hd-senpai-giddy', [40, 265], 0, false, isPlayer);
		animation.add('hd-senpai-happy', [40, 265], 0, false, isPlayer);
		animation.add('hd-senpai-fear-happy', [265], 0, false, isPlayer);
		animation.add('camellia', [266, 267], 0, false, isPlayer);
		animation.add('camelliahalloween', [266, 267], 0, false, isPlayer);
		animation.add('bf-jabibi', [268, 269], 0, false, isPlayer);
		animation.add('hank-antipathy', [270, 271], 0, false, isPlayer);
		animation.add('aldryx', [272, 273], 0, false, isPlayer);
		animation.add('aldryx-shaded', [272, 273], 0, false, isPlayer);
		animation.add('cassette-girl', [274, 275], 0, false, isPlayer);
		animation.add('hallow', [276, 277], 0, false, isPlayer);
		animation.add('hypno-two', [278], 0, false, isPlayer);
		animation.add('missingno', [280, 281], 0, false, isPlayer);
		animation.add('teto', [282, 283], 0, false, isPlayer);
		animation.add('bomberman', [284, 285], 0, false, isPlayer);
		animation.add('prdev', [286, 287], 0, false, isPlayer);
		animation.add('soul-tails', [288, 289], 0, false, isPlayer);
		animation.add('steven-pibby', [290, 291], 0, false, isPlayer);
		animation.add('spongebob-pibby', [292, 293], 0, false, isPlayer);
		animation.add('ruby', [294, 295], 0, false, isPlayer);
		animation.add('ruby-worried', [294, 295], 0, false, isPlayer);
		animation.add('ruby-worried-night', [294, 295], 0, false, isPlayer);
		animation.add('ruby-worried-blue', [294, 295], 0, false, isPlayer);
		animation.add('cjClone', [296, 297], 0, false, isPlayer);
		animation.add('bf-sonic', [298, 299], 0, false, isPlayer);
		animation.add('bf-sonic-flipped', [298, 299], 0, false, isPlayer);
		animation.add('taki', [300, 301], 0, false, isPlayer);
		animation.add('haachama', [302, 303], 0, false, isPlayer);
		animation.add('doxxie', [304, 305], 0, false, isPlayer);
		animation.add('happymouse-bw', [306, 307], 0, false, isPlayer);
		animation.add('momi', [308, 309], 0, false, isPlayer);
		animation.add('snow', [310, 311], 0, false, isPlayer);
		animation.add('mackiepom', [312, 313], 0, false, isPlayer);
		animation.add('rosie', [314, 315], 0, false, isPlayer);
		animation.add('rosie-angry', [314, 315], 0, false, isPlayer);
		animation.add('rosie-furious', [314, 315], 0, false, isPlayer);
		animation.add('cj', [316, 317], 0, false, isPlayer);
		animation.add('cj-ruby', [318, 319], 0, false, isPlayer);
		animation.add('cj-ruby-both', [318, 319], 0, false, isPlayer);
		animation.add('gf-demon', [320, 17], 0, false, isPlayer);
		animation.add('dad-happy', [12, 321], 0, false, isPlayer);
		animation.add('bob2', [322, 323], 0, false, isPlayer);
		animation.add('bob2-night', [322, 323], 0, false, isPlayer);
		animation.add('bosip', [324, 325], 0, false, isPlayer);
		animation.add('peri', [326, 327], 0, false, isPlayer);
		animation.add('bana', [328, 329], 0, false, isPlayer);
		animation.add('mel', [330, 331], 0, false, isPlayer);
		animation.add('cg5', [332, 333], 0, false, isPlayer);
		animation.add('pumpkinpie', [334, 335], 0, false, isPlayer);
		animation.add('mia', [336, 337], 0, false, isPlayer);
		animation.add('mia-lookstraight', [336, 337], 0, false, isPlayer);
		animation.add('mia-lookstraight-blue', [336, 337], 0, false, isPlayer);
		animation.add('mia-wire', [338, 339], 0, false, isPlayer);
		animation.add('bana-wire', [340, 341], 0, false, isPlayer);
		animation.add('sarvente-worried-blue', [342, 43], 0, false, isPlayer);
		animation.add('sarvente-worried-night', [342, 43], 0, false, isPlayer);
		animation.add('bf-senpai-worried', [343, 41], 0, false, isPlayer);
		animation.add('sky-annoyed', [47, 344], 0, false, isPlayer);
		animation.add('bf-aloe-confused', [345, 171], 0, false, isPlayer);
		animation.add('mia-lookstraight-sad-blue', [346], 0, false, isPlayer);
		animation.add('mom-sad', [347], 0, false, isPlayer);
		animation.add('mom-sad-blue', [347], 0, false, isPlayer);
		animation.add('ace', [348, 349], 0, false, isPlayer);
		animation.add('hd-monika', [350, 351], 0, false, isPlayer);
		animation.add('hex-virus', [352, 353], 0, false, isPlayer);
		animation.add('ruv-mad', [354, 45], 0, false, isPlayer);
		animation.add('tankman-mad', [355, 9], 0, false, isPlayer);
		animation.add('hd-monika-angry', [356, 357], 0, false, isPlayer);
		animation.add('bf-smol-ruv', [358, 359], 0, false, isPlayer);
		animation.add('mario', [360, 361], 0, false, isPlayer);
		animation.add('bico-christmas', [362, 363], 0, false, isPlayer);
		animation.add('henry-blue', [364, 365], 0, false, isPlayer);
		animation.add('blantad-blue', [366, 367], 0, false, isPlayer);
		animation.add('bf-pump', [368, 369], 0, false, isPlayer);
		animation.add('senpaighosty-blue', [371], 0, false, isPlayer);
		animation.add('alya', [372, 373], 0, false, isPlayer);
		animation.add('phil', [374, 375], 0, false, isPlayer);
		animation.add('tordbot', [376, 377], 0, false, isPlayer);
		animation.add('b3-mom-sad', [378], 0, false, isPlayer);
		animation.add('b3-mom-mad', [379], 0, false, isPlayer);
		animation.add('starecrown', [380, 381], 0, false, isPlayer);
		animation.add('picoCrazy', [382, 383], 0, false, isPlayer);
		animation.add('bf-cesar', [384, 385], 0, false, isPlayer);
		animation.add('bf-cesar-scream', [384, 385], 0, false, isPlayer);
		animation.add('bf-demoncesar', [386, 387], 0, false, isPlayer);
		animation.add('bf-demoncesar-cas', [386, 387], 0, false, isPlayer);
		animation.add('kkslider', [388, 389], 0, false, isPlayer);
		animation.add('beardington', [390, 391], 0, false, isPlayer);
		animation.add('steve', [392, 393], 0, false, isPlayer);
		animation.add('noke', [394, 395], 0, false, isPlayer);
		animation.add('cyrix', [396, 397], 0, false, isPlayer);
		animation.add('cyrix-crazy', [398, 399], 0, false, isPlayer);
		animation.add('sh-carol', [400, 401], 0, false, isPlayer);
		animation.add('senpai-glitch', [402, 403], 0, false, isPlayer);
		animation.add('spirit-glitch', [404, 405], 0, false, isPlayer);
		animation.add('sarv-ruv', [406, 407], 0, false, isPlayer);
		animation.add('sarv-ruv-both', [406, 407], 0, false, isPlayer);
		animation.add('piconjo', [408, 409], 0, false, isPlayer);
		animation.add('bb', [410, 411], 0, false, isPlayer);
		animation.add('parents-christmas-soft', [412, 413], 0, false, isPlayer);
		animation.add('bf-kaity', [414, 415], 0, false, isPlayer);
		animation.add('bf-kaity-car', [414, 415], 0, false, isPlayer);
		animation.add('sadmouse-bw', [416, 417], 0, false, isPlayer);
		animation.add('bf-senpai-tankman', [418, 419], 0, false, isPlayer);
		animation.add('calli', [420, 421], 0, false, isPlayer);
		animation.add('lucian', [422, 423], 0, false, isPlayer);
		animation.add('abby', [424, 425], 0, false, isPlayer);
		animation.add('abby-mad', [424, 425], 0, false, isPlayer);
		animation.add('ron', [426, 427], 0, false, isPlayer);
		animation.add('nonsense', [428, 429], 0, false, isPlayer);
		animation.add('nonsense-pissed', [428, 429], 0, false, isPlayer);
		animation.add('nonsense-mad', [428, 429], 0, false, isPlayer);
		animation.add('nonsense-god', [430], 0, false, isPlayer);
		animation.add('eteled2', [432, 433], 0, false, isPlayer);
		animation.add('pshaggy', [434, 435], 0, false, isPlayer);
		animation.add('glitched-bob', [436, 437], 0, false, isPlayer);
		animation.add('bf-spongebob', [438, 439], 0, false, isPlayer);
		animation.add('peasus', [440, 441], 0, false, isPlayer);
		animation.add('garcellodead', [442, 443], 0, false, isPlayer);
		animation.add('kapi-angry', [444], 0, false, isPlayer);
		animation.add('qt-kb', [445], 0, false, isPlayer);
		animation.add('duet-sm', [446, 447], 0, false, isPlayer);
		animation.add('parents-christmas-angel', [448, 449], 0, false, isPlayer);
		animation.add('monika-real', [450, 451], 0, false, isPlayer);
		animation.add('natsuki', [452, 453], 0, false, isPlayer);
		animation.add('yuri', [454, 455], 0, false, isPlayer);
		animation.add('sayori', [456, 457], 0, false, isPlayer);
		animation.add('taeyai', [458, 459], 0, false, isPlayer);
		animation.add('wooper', [460, 461], 0, false, isPlayer);
		animation.add('woopermellia', [460, 461], 0, false, isPlayer);
		animation.add('bf-aloe-old', [462, 463], 0, false, isPlayer);
		animation.add('mia-old', [464, 465], 0, false, isPlayer);
		animation.add('mia-wire-old', [466, 467], 0, false, isPlayer);
		animation.add('hd-monika-old', [468, 469], 0, false, isPlayer);
		animation.add('hd-monika-angry-old', [470, 471], 0, false, isPlayer);
		animation.add('sunday-old', [472, 473], 0, false, isPlayer);
		animation.add('omega-angry', [474, 475], 0, false, isPlayer);
		animation.add('dust-sans', [476, 477], 0, false, isPlayer);
		animation.add('exe-bw', [478, 479], 0, false, isPlayer);
		animation.add('sadmouse', [480, 481], 0, false, isPlayer);
		animation.add('mami', [482, 483], 0, false, isPlayer);
		animation.add('macy', [484, 485], 0, false, isPlayer);
		animation.add('kalisa', [486, 487], 0, false, isPlayer);
		animation.add('exe', [488, 489], 0, false, isPlayer);
		animation.add('maijin', [490, 491], 0, false, isPlayer);
		animation.add('cablecrow', [492, 493], 0, false, isPlayer);
		animation.add('bb-tired-blue', [494], 0, false, isPlayer);
		animation.add('bf-blue', [495], 0, false, isPlayer);
		animation.add('sayori-sad', [496, 497], 0, false, isPlayer);
		animation.add('sayori-sad-blue', [496, 497], 0, false, isPlayer);
		animation.add('lord-x', [498, 499], 0, false, isPlayer);
		animation.add('scott', [500, 501], 0, false, isPlayer);
		animation.add('amor-ex', [502, 503], 0, false, isPlayer);
		animation.add('exTricky', [504, 505], 0, false, isPlayer);
		animation.add('bluskys', [506, 507], 0, false, isPlayer);
		animation.add('bf-ex-night', [508, 509], 0, false, isPlayer);
		animation.add('void', [510, 511], 0, false, isPlayer);
		animation.add('little-man', [512, 513], 0, false, isPlayer);
		animation.add('calebcity', [514, 515], 0, false, isPlayer);
		animation.add('kb', [516, 517], 0, false, isPlayer);
		animation.add('qt', [518, 519], 0, false, isPlayer);
		animation.add('makocorrupt', [520, 521], 0, false, isPlayer);
		animation.add('bf-pixel-neon', [522, 523], 0, false, isPlayer);
		animation.add('king', [524, 525], 0, false, isPlayer);
		animation.add('monokuma', [526, 527], 0, false, isPlayer);	
		animation.add('beebz', [528, 529], 0, false, isPlayer);
		animation.add('hypno', [530, 531], 0, false, isPlayer);
		animation.add('hypno-dark', [530, 531], 0, false, isPlayer);
		animation.add('yukichi-police', [532, 533], 0, false, isPlayer);
		animation.add('angrybob', [534, 535], 0, false, isPlayer);
		animation.add('coco2', [536, 537], 0, false, isPlayer);
		animation.add('sketch', [538, 539], 0, false, isPlayer);
		animation.add('maijin-new', [540, 541], 0, false, isPlayer);
		animation.add('maijin-new-flipped', [540, 541], 0, false, isPlayer);
		animation.add('beast-sonic', [542, 543], 0, false, isPlayer);
		animation.add('beast-sonic-flipped', [542, 543], 0, false, isPlayer);
		animation.add('trollge', [544, 545], 0, false, isPlayer);
		animation.add('demongf', [546, 547], 0, false, isPlayer);
		animation.add('demongf-city', [546, 547], 0, false, isPlayer);
		animation.add('yukichi', [548, 549], 0, false, isPlayer);
		animation.add('yukichi-mad', [550, 551], 0, false, isPlayer);
		animation.add('yukichi-mad-city', [550, 551], 0, false, isPlayer);
		animation.add('brody', [552, 553], 0, false, isPlayer);
		animation.add('austin', [554, 555], 0, false, isPlayer);
		animation.add('bf-kitty', [556, 557], 0, false, isPlayer);
		animation.add('happymouse', [558, 559], 0, false, isPlayer);
		animation.add('kirbo', [560, 561], 0, false, isPlayer);
		animation.add('papyrus', [562, 563], 0, false, isPlayer);
		animation.add('midas', [564, 565], 0, false, isPlayer);
		animation.add('midas-r', [564, 565], 0, false, isPlayer);
		animation.add('midas-double', [564, 565], 0, false, isPlayer);
		animation.add('foks', [566, 567], 0, false, isPlayer);
		animation.add('pompom', [568, 569], 0, false, isPlayer);
		animation.add('anders', [570, 571], 0, false, isPlayer);
		animation.add('anders-fearsome', [572, 573], 0, false, isPlayer);
		animation.add('dr-springheel', [574, 575], 0, false, isPlayer);
		animation.add('dr-springheel-mad', [574, 575], 0, false, isPlayer);
		animation.add('jester', [576, 577], 0, false, isPlayer);
		animation.add('hubert', [578, 579], 0, false, isPlayer);
		animation.add('tornsketchy', [580, 581], 0, false, isPlayer);
		animation.add('bf-demoncesar-bw', [582, 583], 0, false, isPlayer);
		animation.add('sanford', [584, 585], 0, false, isPlayer);
		animation.add('ridzak', [586, 587], 0, false, isPlayer);
		animation.add('jevil', [588, 589], 0, false, isPlayer);
		animation.add('skye', [590, 591], 0, false, isPlayer);
		animation.add('skye-r', [590, 591], 0, false, isPlayer);
		animation.add('sky-pissed', [592], 0, false, isPlayer);
		animation.add('spooky-pelo', [593, 594], 0, false, isPlayer);
		animation.add('lila-pelo', [595, 596], 0, false, isPlayer);
		animation.add('sasha', [597, 598], 0, false, isPlayer);
		animation.add('happymouse2', [559, 599], 0, false, isPlayer);
		animation.add('sunky', [600, 601], 0, false, isPlayer);
		animation.add('herobrine', [602, 603], 0, false, isPlayer);
		animation.add('freddy', [604, 605], 0, false, isPlayer);
		animation.add('mokey', [606, 607], 0, false, isPlayer);
		animation.add('geese', [608, 609], 0, false, isPlayer);
		animation.add('geese-minus', [608, 609], 0, false, isPlayer);
		animation.add('geese-fly', [608, 609], 0, false, isPlayer);
		animation.add('glitch', [610, 611], 0, false, isPlayer);
		animation.add('glitch-angry', [610, 611], 0, false, isPlayer);
		animation.add('bf-kapi-pixel', [612, 613], 0, false, isPlayer);
		animation.add('static', [614, 615], 0, false, isPlayer);
		animation.add('cheeky', [616, 617], 0, false, isPlayer);
		animation.add('bf-demoncesar-trollge', [618, 619], 0, false, isPlayer);
		animation.add('myra', [620, 621], 0, false, isPlayer);
		animation.add('gar-spirit', [622, 623], 0, false, isPlayer);
		animation.add('pinkie', [624, 625], 0, false, isPlayer);
		animation.add('yuri-crazy', [626, 627], 0, false, isPlayer);
		animation.add('trickward', [628, 629], 0, false, isPlayer);
		animation.add('starzgf', [630], 0, false, isPlayer);
		animation.add('gf5', [630], 0, false, isPlayer);
		animation.add('bigmonika', [631, 632], 0, false, isPlayer);
		animation.add('bigmonika-dead', [631, 632], 0, false, isPlayer);
		animation.add('baldi-angry', [633, 634], 0, false, isPlayer);
		animation.add('neonight', [635, 636], 0, false, isPlayer);
		animation.add('ina', [637, 638], 0, false, isPlayer);
		animation.add('ina2', [637, 638], 0, false, isPlayer);
		animation.add('gold', [639], 0, false, isPlayer);
		animation.add('gold-side', [639], 0, false, isPlayer);
		animation.add('rushia', [640, 641], 0, false, isPlayer);
		animation.add('tails', [642, 643], 0, false, isPlayer);
		animation.add('sonic', [644, 645], 0, false, isPlayer);
		animation.add('sonic-forced', [644, 645], 0, false, isPlayer);
		animation.add('sonic-mad', [646, 647], 0, false, isPlayer);
		animation.add('retro', [648, 649], 0, false, isPlayer);
		animation.add('sakuroma', [650, 651], 0, false, isPlayer);
		animation.add('rshaggy', [652, 653], 0, false, isPlayer);
		animation.add('alucard', [654, 655], 0, false, isPlayer);
		animation.add('bf-sticky', [656, 657], 0, false, isPlayer);
		animation.add('amor', [658, 659], 0, false, isPlayer);
		animation.add('bipolarmouse', [660, 661], 0, false, isPlayer);
		animation.add('mami-holy', [662, 663], 0, false, isPlayer);
		animation.add('hank', [664, 665], 0, false, isPlayer);
		animation.add('auditor', [666, 667], 0, false, isPlayer);
		animation.add('oswald-happy', [668, 669], 0, false, isPlayer);
		animation.add('oswald-angry', [668, 669], 0, false, isPlayer);
		animation.add('nyancat', [670, 671], 0, false, isPlayer);
		animation.add('bf-tc', [672, 673], 0, false, isPlayer);
		animation.add('woody', [674, 675], 0, false, isPlayer);
		animation.add('blantad-scream2', [676], 0, false, isPlayer);
		animation.add('midas-shadow', [677, 678], 0, false, isPlayer);
		animation.add('arch', [679], 0, false, isPlayer);
		animation.add('hellbob', [680, 681], 0, false, isPlayer);
		animation.add('cerbera', [682, 683], 0, false, isPlayer);
		animation.add('bf-sans-new', [684, 685], 0, false, isPlayer);
		animation.add('zipper', [686, 687], 0, false, isPlayer);
		animation.add('mara', [688, 689], 0, false, isPlayer);
		animation.add('richard1', [690, 691], 0, false, isPlayer);
		animation.add('bf-bbpanzu', [692, 693], 0, false, isPlayer);
		animation.add('flexy', [694, 695], 0, false, isPlayer);
		animation.add('v-calm', [696, 697], 0, false, isPlayer);
		animation.add('kadedev', [698, 699], 0, false, isPlayer);
		animation.add('daidem', [700, 701], 0, false, isPlayer);
		animation.add('bf-six', [702, 703], 0, false, isPlayer);
		animation.add('twinstwo', [704, 705], 0, false, isPlayer);
		animation.add('exe-front', [706, 707], 0, false, isPlayer);
		animation.add('bf-shirogane', [708, 709], 0, false, isPlayer);
		animation.add('fujiwara', [710, 711], 0, false, isPlayer);
		animation.add('nikusa', [712, 713], 0, false, isPlayer);
		animation.add('nikusa-shaded', [712, 713], 0, false, isPlayer);
		animation.add('faker', [714, 715], 0, false, isPlayer);
		animation.add('exe-revie', [716, 717], 0, false, isPlayer);
		animation.add('bf-cryingchild', [718, 719], 0, false, isPlayer);
		animation.add('cc', [720, 721], 0, false, isPlayer);

		if (animation.getByName(char) != null) {
			animation.play(char);
		}
		else {
			changeIcon(char);
		}		
		
		if (char.startsWith('senpai') || char.contains('pixel') || char.startsWith('spirit') || char.startsWith('monika') && char != 'monika-real')
			antialiasing = false;
	}

	override function update(elapsed:Float)
	{
		super.update(elapsed);

		if (sprTracker != null)
			setPosition(sprTracker.x + sprTracker.width + 10, sprTracker.y - 30);
	}
}
